repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]

  - repo: local
    hooks:
      - id: no-yml-extension
        name: Enforce .yaml extension instead of .yml
        entry: No .yml extensions allowed. Use .yaml instead.
        language: fail
        files: \.yml$
