name: Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run prek
        uses: j178/prek-action@v2
